const express=require('express')
const dotenv=require('dotenv').config({path:'./config/config.env'})
var cookieParser = require('cookie-parser')
const app=express()
app.use(cookieParser())
const routes=require('./routers/routes.js')
const roles=require("./routers/roles.js")
const rolespermission=require("./routers/role_permission.js")
const groups=require('./routers/group.js')
const connections=require('./config/connection.js')
const permissions = require('./routers/permission.js')
app.use(express.json())
app.use('/api/',routes)
app.use("/roleapi/",roles );
app.use('/permissionroute/',permissions)
app.use('/rolePermission/',rolespermission)
app.use('/groupapi/',groups)
connections()
app.listen(process.env.PORT,()=>{
    console.log('server is started at 8080')
})