const express = require('express')
const dotenv = require('dotenv').config({ path: './config/config.env' })
var cookieParser = require('cookie-parser')
const app = express()
app.use(cookieParser())
const routes = require('./routers/routes.js')
const roles = require("./routers/roles.js")
const rolespermission = require("./routers/role_permission.js")
const groups = require('./routers/group.js')
const connections = require('./config/connection.js')
const permissions = require('./routers/permission.js')
const leads = require('./routers/leads.js')
const orders=require('./routers/orders.js')
const categories=require('./routers/categories.js')
const payment=require('./routers/payment.js')
const activity_log=require('./routers/activity_logs.js')
const imports=require('./routers/import.js')
const orderitemss=require('./routers/order_item.js')
const products=require('./routers/products.js')
const dealers=require('./routers/dealer.js')
const departments=require('./routers/departement.js')
const employees=require('./routers/employee.js')
const task=require('./routers/task.js')
const assignment=require('./routers/assignment.js')
app.use(express.json())
app.use('/api/', routes)
app.use("/roleapi/", roles);
app.use('/permissionroute/', permissions)
app.use('/rolePermission/', rolespermission)
app.use('/groupapi/', groups)
app.use('/leads/', leads)
app.use('/orders/', orders)
app.use('/categories/',categories)
app.use('/payment/',payment)
app.use('/activity/',activity_log)
app.use('/history/',imports)
app.use('/orderitemss/',orderitemss)
app.use('/products/',products)
app.use('/dealers/',dealers)
app.use('/department/',departments)
app.use('/employee/',employees,task)
app.use('/assignments/',assignment)
connections()

app.listen(process.env.PORT, () => {
    console.log('server is started at 8080')
})